sudo: false

addons:
  apt:
    packages:
    - ffmpeg

cache:
  directories:
  - $HOME/env

language: python

notifications:
  email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

env:
    - ENABLE_NUMBA=false
    - ENABLE_NUMBA=true

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    # install your own package into the environment
    # pip install -e rather than setup.py, so that coverage can find the source
    - pip install --pre -e .[tests]

script:
    - python --version
    - nosetests --with-coverage --cover-erase --cover-package=librosa -v -w tests/

after_success:
    - coveralls
    - pip uninstall -y librosa

after_failure:
    - pip uninstall -y librosa
